# Generated by Django 3.2.7 on 2021-09-14 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smile', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ModelProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_inds', models.IntegerField()),
                ('mutation_chance', models.FloatField()),
                ('generations', models.IntegerField()),
                ('use_crippen', models.BooleanField(default=False)),
                ('smile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapex.smilesmodel')),
            ],
        ),
    ]
