# Generated by Django 3.2.7 on 2021-09-16 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelproperties',
            name='smile',
        ),
        migrations.AddField(
            model_name='modelproperties',
            name='email',
            field=models.EmailField(max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelproperties',
            name='smiles',
            field=models.TextField(max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SmilesModel',
        ),
    ]
