# Generated by Django 3.2.7 on 2021-09-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapex', '0006_alter_centers_pharmacophore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Centers',
        ),
    ]
