# Generated by Django 3.2.7 on 2021-09-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapex', '0007_delete_centers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacophore',
            name='x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacophore',
            name='y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacophore',
            name='z',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
