# Generated by Django 3.2.7 on 2021-10-03 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapex', '0010_alter_modelproperties_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelproperties',
            name='link',
        ),
        migrations.AddField(
            model_name='modelproperties',
            name='distance',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_url', models.URLField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapex.modelproperties')),
            ],
        ),
    ]
